id: P4155B40C
initial_creation_type: ocr
source_metadata:
  volumes:
    69e7982913474cc19707ac59f1928f4e:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: ཆོས་ཐམས་ཅད་རང་བཞིན་མེད་པ་ཉིད་དུ་གྲུབ་པ།
      total_pages: 1557
      volume_number: 62
